# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!
 
linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

permissions_path = '../node_modules/react-native-permissions/ios'

rn_maps_path = '../node_modules/react-native-maps'
pod 'react-native-google-maps', :path => rn_maps_path
pod 'GoogleMaps'
pod 'Google-Maps-iOS-Utils'

pod 'react-native-in-app-review', :path => '../node_modules/react-native-in-app-review'

permissions_path = '../node_modules/react-native-permissions/ios'
pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways/Permission-LocationAlways.podspec"
pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse/Permission-LocationWhenInUse.podspec"

target 'ETravelMateDriver' do
  config = use_native_modules!
  pod 'TrustKit'

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'react-native-document-picker', :path => '../node_modules/react-native-document-picker'

  pod 'rn-fetch-blob', :path => '../node_modules/rn-fetch-blob'

  pod 'GoogleUtilities', :modular_headers => true
  pod 'FirebaseCore', :modular_headers => true

  
# pod 'react-native-mapmyindia-intouch', :path => '../node_modules/mapmyindia-intouch-react-native-sdk'
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'

  target 'ETravelMateDriverTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
     # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    installer.pods_project.targets.each do |target|
      if target.name == 'React-Core-AccessibilityResources'
      target.build_phases.each do |build_phase|
        if build_phase.respond_to?(:remove_from_project)
          build_phase.remove_from_project
        end
      end
    end
       target.build_configurations.each do |config|
      config.build_settings['EXCLUDED_ARCHS[sdk=iphonesimulator*]'] = "arm64"
      end
    end
  end
end
